---
title: "effects_model"
author: "Gulzina Kuttubekova"
date: "6/6/2020"
output: pdf_document
---



```{r, include=FALSE}
library(dplyr)
library(ggplot2)
library(reshape)
library(invgamma)
library(ggpubr)
library(mvtnorm)
```


Fit effects model to get design matrix:
```{r}
# model 1
lm3 <- lm(y ~ Region, data = covid)
X3 <- model.matrix(lm3)
```

```{r}
betahat3 <- find_betahat(omega, X3, covid$y)
betahat3
```

```{r}
sigmasqhat3 <- find_sigmasqhat(omega, X3, covid$y, betahat3)
sigmasqhat3
```

Sample sigmasq from posterior:
```{r}
# constants
p3 <- ncol(X3)

mc3 <- data.frame(
    sigmasq = rinvgamma(N, shape = (n-p3)/2, 
                        rate = (n-p3)*sigmasqhat3[1,1]/2))

# add beta samples
beta3 <- c()

# covariance matrix
sd_beta3 <- solve(t(X3)%*%solve(omega)%*%X3)

for (i in 1:N) {
    temp <- rmvnorm(1, mean = betahat3[,1],
                          sigma = mc3$sigmasq[i] * sd_beta3)
    
    beta3 <- rbind(beta3, temp[1,])
}

mc3 <- cbind(mc3, beta3)
```

Confidence intervals
```{r}
apply(mc3, 2, quantile, probs = c(0.025, 0.5, 0.975))
```

```{r}
betamap3 <- apply(mc3[,-1], 2, mean)
betamap3
```

Get estimates for different expected infections for different counties
```{r}
X3_est <- X3[counties,]
estimate_infections(X3_est, betamap3)
```




